const res = {
  status_code: 10,
  lang: "javascript",
  run_success: true,
  status_runtime: "60 ms",
  memory: 41888000,
  code_answer: ["[0,1]"],
  code_output: [],
  std_output: ["", ""],
  elapsed_time: 88,
  task_finish_time: 1675135087093,
  expected_status_code: 10,
  expected_lang: "cpp",
  expected_run_success: true,
  expected_status_runtime: "0",
  expected_memory: 6312000,
  expected_code_answer: ["[0,1]"],
  expected_code_output: [],
  expected_std_output: ["", ""],
  expected_elapsed_time: 10,
  expected_task_finish_time: 1675133799804,
  correct_answer: true,
  compare_result: "1",
  total_correct: 1,
  total_testcases: 1,
  runtime_percentile: null,
  status_memory: "41.9 MB",
  memory_percentile: null,
  pretty_lang: "JavaScript",
  submission_id: "runcode_1675135086.8690264_eE5DbTbSOa",
  status_msg: "Accepted",
  state: "SUCCESS",
};
